export const PRIMARY_COLOR        = '#fcee9f'
export const PRIMARY_COLOR_LIGHT  = '#f7f1cd'
export const PRIMARY_COLOR_DARK   = '#f7de54' 
export const WHITE_COLOR          = 'white' 
export const BLACK_COLOR          = 'black' 
export const GRAY_COLOR           = '#828282' 